# Generated by Django 5.1.4 on 2026-01-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_taluka_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('pattern', models.CharField(choices=[('radial', 'Radial'), ('bias', 'Bias'), ('tubeless', 'Tubeless'), ('tube_type', 'Tube Type')], db_index=True, max_length=50)),
                ('type', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear'), ('spare', 'Spare'), ('all_position', 'All Position')], db_index=True, max_length=50)),
                ('company', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='store.driver')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tyres', to='store.vendor')),
            ],
            options={
                'verbose_name_plural': 'Tyres',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tyre_no'], name='store_tyre_tyre_no_330dc6_idx'), models.Index(fields=['pattern'], name='store_tyre_pattern_037d9b_idx'), models.Index(fields=['type'], name='store_tyre_type_48a828_idx'), models.Index(fields=['company'], name='store_tyre_company_e9df35_idx')],
            },
        ),
    ]
