# Generated by Django 5.1.4 on 2026-01-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_vendor_tyre'),
    ]

    operations = [
        migrations.CreateModel(
            name='mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
