# Generated by Django 5.1.4 on 2026-01-30 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_mechanic_office_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='store.office_location'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('office_location', 'name')},
        ),
    ]
