# Generated by Django 3.2.15 on 2024-03-07 06:36

import datetime
from django.db import migrations, models
from datetime import timezone as dt_timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_alter_builty_expense_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty_expense',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='diesel_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc)),
        ),
        migrations.AlterField(
            model_name='fund',
            name='entry_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='other_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc)),
        ),
        migrations.AlterField(
            model_name='salary',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transfer_fund',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc)),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='entry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 7, 6, 36, 7, 373230, tzinfo=dt_timezone.utc)),
        ),
    ]
