# Generated by Django 5.1.4 on 2026-01-28 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0087_alter_builty_expense_entry_date'),
        ('store', '0016_vendor_tyre'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_expense',
            name='tyre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_expenses', to='store.tyre'),
        ),
    ]
