# Generated by Django 5.1.4 on 2026-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0088_truck_expense_tyre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_expense',
            name='tyre',
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='tyre_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
