# Generated by Django 5.1.4 on 2026-01-28 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0089_remove_truck_expense_tyre_truck_expense_tyre_no'),
        ('store', '0016_vendor_tyre'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_expense',
            name='company',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.driver'),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='pattern',
            field=models.CharField(blank=True, choices=[('radial', 'Radial'), ('bias', 'Bias'), ('tubeless', 'Tubeless'), ('tube_type', 'Tube Type')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='type',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear'), ('spare', 'Spare'), ('all_position', 'All Position')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.vendor'),
        ),
    ]
