# Generated by Django 5.1.4 on 2026-01-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0090_truck_expense_company_truck_expense_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_expense',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='expense_type',
            field=models.CharField(choices=[('tyre', 'Tyre Expense'), ('mechanic', 'Mechanic/Spare Part Expense'), ('other', 'Other Truck Expense')], db_index=True, default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='labour_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='mechanic_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='spare_part_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='truck_expense',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
