# Generated by Django 5.1.4 on 2026-01-30 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0091_truck_expense_cost_truck_expense_expense_type_and_more'),
        ('store', '0017_mechanic_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck_expense',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_expenses', to='store.mechanic'),
        ),
    ]
