# Generated by Django 5.1.4 on 2026-01-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0092_truck_expense_mechanic_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck_expense',
            name='mechanic_name',
        ),
        migrations.AlterField(
            model_name='truck_expense',
            name='pattern',
            field=models.CharField(blank=True, choices=[('radial', 'Radial'), ('nylon', 'Nylon')], db_index=True, max_length=50, null=True),
        ),
    ]
