# Generated by Django 5.1.4 on 2026-01-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0093_remove_mechanic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_expense',
            name='pattern',
            field=models.CharField(blank=True, choices=[('radial', 'Radial'), ('nylon', 'Nylon'), ('remoulded', 'Remoulded'), ('reused', 'Reused')], db_index=True, max_length=50, null=True),
        ),
    ]
