# Generated by Django 5.1.4 on 2025-11-07 05:46

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_taluka_name'),
        ('transactions', '0078_alter_ack_history_update_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ack',
            options={'ordering': ['-challan_date']},
        ),
        migrations.AlterModelOptions(
            name='ack_history',
            options={'ordering': ['-update_date']},
        ),
        migrations.AlterModelOptions(
            name='builty',
            options={'ordering': ['-DC_date'], 'verbose_name_plural': 'Builty Records'},
        ),
        migrations.AlterModelOptions(
            name='request_edit',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='ack',
            name='challan_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack',
            name='challan_number',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ack',
            name='voucher_payment_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='ack_history',
            name='challan_date_before',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='ack_history',
            name='challan_number_before',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ack_history',
            name='update_date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='DC_date',
            field=models.DateField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='consignee',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='deleted',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='delivery_no',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='builty',
            name='editable',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='builty',
            name='ex_for',
            field=models.CharField(choices=[('for', 'for'), ('ex', 'ex')], db_index=True, default='for', max_length=50),
        ),
        migrations.AlterField(
            model_name='builty',
            name='mode',
            field=models.CharField(choices=[('cash', 'cash'), ('online', 'online')], db_index=True, default='cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='request_edit',
            name='history',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='request_edit',
            name='status',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='ack',
            index=models.Index(fields=['challan_number'], name='transaction_challan_48acd4_idx'),
        ),
        migrations.AddIndex(
            model_name='ack',
            index=models.Index(fields=['voucher_payment_status'], name='transaction_voucher_25cafa_idx'),
        ),
        migrations.AddIndex(
            model_name='ack_history',
            index=models.Index(fields=['update_date'], name='transaction_update__2fa928_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['builty_no'], name='transaction_builty__896504_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['DC_date'], name='transaction_DC_date_14f087_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['mode'], name='transaction_mode_09e084_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['deleted'], name='transaction_deleted_4d6dac_idx'),
        ),
        migrations.AddIndex(
            model_name='builty',
            index=models.Index(fields=['company', 'DC_date'], name='transaction_company_c23d79_idx'),
        ),
        migrations.AddIndex(
            model_name='request_edit',
            index=models.Index(fields=['status'], name='transaction_status_11ae7f_idx'),
        ),
        migrations.AddIndex(
            model_name='request_edit',
            index=models.Index(fields=['history'], name='transaction_history_42c0ac_idx'),
        ),
    ]
