# Generated by Django 5.1.4 on 2026-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0079_alter_ack_options_alter_ack_history_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builty',
            name='builty_no',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
